# orchestrator/tasks/main.yml
---
- name: Start LXD container for MicroK8s
  community.general.lxd_container:
    name: microk8s
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases/
      protocol: simplestreams
      alias: "22.04"
    profiles: ["microk8s"]
    wait_for_ipv4_addresses: true
    timeout: 600
  tags:
    - default
    - setup

# - name: Install MicroK8s in an LXD container
#   delegate_to: microk8s
#   ansible.builtin.shell: lxc exec microk8s -- sudo snap install microk8s --classic
#
# - name: Load AppArmor on boot
#   delegate_to: microk8s
#   ansible.builtin.shell: |
#     lxc shell microk8s
#     cat > /etc/rc.local <<EOF
#     #!/bin/bash
#     apparmor_parser --replace /var/lib/snapd/apparmor/profiles/snap.microk8s.*
#     exit 0
#     EOF
#     chmod +x /etc/rc.local

- name: Install MicroK8s in an LXD container
  community.general.lxc_container:
    name: microk8s
    container_command: lxc exec microk8s -- sudo snap install microk8s --classic
  tags:
    - default
    - setup

- name: Load AppArmor on boot
  community.general.lxc_container:
    name: microk8s
    container_command: |
      lxc shell microk8s
      cat > /etc/rc.local <<EOF
      #!/bin/bash
      apparmor_parser --replace /var/lib/snapd/apparmor/profiles/snap.microk8s.*
      exit 0
      EOF
      chmod +x /etc/rc.local
  tags:
    - default
    - setup

