# security/tasks/hardened_malloc.yml
---
- name: Install hardened-malloc
  community.general.apk:
    name: hardened-malloc
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
    state: present
    update_cache: true
  tags:
    - default
    - setup

- name: Enable hardened-malloc
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: LD_PRELOAD="/usr/lib/libhardened_malloc.so"
    state: present
  tags:
    - default
    - setup

