# tasks/main.yml
---
- name: Install hardened-malloc
  community.general.apk:
    name: hardened-malloc
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
    state: present
    update_cache: true
  notify:
    - Enable hardened-malloc
  tags:
  - default
  - setup
