# tasks/main.yml
---
- name: Add Alpine Linux Edge with testing repository
  ansible.builtin.command: echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
  
- name: Install hardened-malloc
  community.general.apk:
    name: hardened-malloc
    state: present
    update_cache: true
  notify:
    - Enabled hardened-malloc

- name: Enable hardened-malloc
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: LD_PRELOAD="/usr/lib/libhardened_malloc.so"
    state: present
