# idp/tasks/freeipa.yaml
---
- name: Launch FreeIPA container
  community.docker.docker_container:
    name: freeipa
    image: freeipa/freeipa-server:fedora-41
    state: started
  tags:
    - default
    - setup
