# idp/tasks/freeipa.yaml
---
- name: Launch FreeIPA container
  community.docker.docker_container:
    name: freeipa
    image: freeipa/freeipa-server:fedora-41
    state: started
    hostname: freeipa.local
    ports:
      - "53:53/tcp"
      - "80:80/tcp"
      - "53:53/udp"
      - "88:88/udp"
      - "88:88/tcp"
      - "389:389/tcp"
      - "443:443/tcp"
      - "123:123/udp"
      - "464:464/tcp"
      - "636:636/tcp"
      - "464:464/udp"
    cgroupns_mode: "host"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  tags:
    - default
    - setup
