---
- name: Install Docker
  community.general.apk:
    name: docker
    state: present
    update_cache: true
  register: pkg_docker_install
  tags:
    - default
    - setup

- name: Get Docker binary path
  ansible.builtin.command: which docker
  register: path_docker_binary
  when: pkg_docker_install == 0
  changed_when: false

- name: Enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
    runlevel: default
  when: pkg_docker_install == 0
  tags:
    - default
    - setup

- name: Create Docker serviceaccount
  ansible.builtin.user:
    name: dockeruser
    system: true
    shell: /bin/false
    create_home: false
    append: true
    groups: docker
  when: pkg_docker_install == 0
  tags:
    - default
    - setup

- name: Grant limited permissions to Docker serviceaccount
  community.general.sudoers:
    name: dockeruser
    user: dockeruser
    commands:
      - "{{ path_docker_binary.stdout }} ps"
      - "{{ path_docker_binary.stdout }} run"
    nopassword: true
  when: pkg_docker_install == 0
  tags:
    - default
    - setup

