# handlers/main.yml
---
- name: Enable user access
  block:
  - name: Check user access to LXD
    ansible.builtin.getent:
      database: lxd
      key: "{{ ansible_user }}"
    register: lxd_access

  - name: Grant user access to LXD
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: lxd
      append: true
    when: lxd_access.rc != 0

  - name: Create LXD group
    ansible.builtin.group:
      name: lxd
      state: present

- name: Enable LXD service
  ansible.builtin.service:
    name: lxd
    enabled: true
    state: started
    runlevel: default

- name: Initialize LXD
  ansible.builtin.shell: |
    cat <<EOF | lxd init --preseed
    config:
      core.https_address: 192.168.1.1:9999
      images.auto_update_interval: 15
    networks:
    - name: lxdbr0
      type: bridge
      config:
        ipv4.address: auto
        ipv6.address: none
    EOF


